import { getSettings } from './data.js';

const links=[['Home','index.html'],['Rooms','rooms.html'],['Book Now','booking.html'],['Food & Drinks','order.html'],['Gallery','gallery.html'],['About','about.html'],['Contact','contact.html']];
const path=location.pathname.split('/').pop() || 'index.html';
const icon={phone:'<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="h-4 w-4"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.8 19.8 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.12 4.18 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.12.9.33 1.78.62 2.63a2 2 0 0 1-.45 2.11L8 9.73a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.85.29 1.73.5 2.63.62A2 2 0 0 1 22 16.92Z"/></svg>',calendar:'<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="h-4 w-4"><rect width="18" height="18" x="3" y="4" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/></svg>',menu:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="h-6 w-6"><path d="M4 6h16M4 12h16M4 18h16"/></svg>',close:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="h-6 w-6"><path d="m6 6 12 12M18 6 6 18"/></svg>'};
const whatsapp=n=>`https://wa.me/${n}?text=Hello%20L-Rina%20Apartment%2C%20I%20would%20like%20to%20enquire%20about%20availability.`;
export async function renderLayout(){ const settings=await getSettings(); const phone=settings.phone_display||'08127057823', wa=settings.whatsapp_number||'2348127057823', email=settings.email||'Lrinahomesluxuryapartment8@gmail.com', address=settings.address||'No 2 Francis Omojiade Crescent, off Howard Edafe Street, Eti-Osa, Lagos 105102, Lagos, Nigeria';
 document.querySelector('#site-header').innerHTML=`<nav id="site-nav" class="fixed top-0 left-0 right-0 z-50 bg-transparent py-5 transition-all duration-500"><div class="container-lr flex items-center justify-between"><a href="index.html" class="flex items-center gap-2"><span class="font-serif text-2xl font-bold nav-brand">L-Rina</span><span class="text-xs uppercase tracking-[.2em] font-light nav-accent">Apartment</span></a><div class="hidden lg:flex items-center gap-8">${links.map(([label,href])=>`<a href="${href}" class="nav-link relative text-sm font-medium tracking-wide">${label}<span class="absolute -bottom-1 left-0 h-0.5 bg-amber-600 transition-all ${path===href?'w-full':'w-0 group-hover:w-full'}"></span></a>`).join('')}</div><div class="hidden lg:flex items-center gap-4"><a href="${whatsapp(wa)}" target="_blank" rel="noopener" class="nav-whatsapp flex items-center gap-2 text-sm font-medium">${icon.phone} WhatsApp</a><a href="booking.html" class="btn-primary text-sm">${icon.calendar} Book Now</a></div><button id="menu-toggle" class="lg:hidden text-white" aria-label="Toggle menu" aria-expanded="false">${icon.menu}</button></div></nav><div id="mobile-drawer" class="fixed inset-0 z-40 invisible lg:hidden"><div id="mobile-overlay" class="absolute inset-0 bg-black/60 opacity-0 transition-opacity"></div><div id="mobile-panel" class="absolute top-0 right-0 h-full w-[300px] max-w-[85vw] translate-x-full bg-white shadow-2xl transition-transform"><div class="pt-24 px-6 flex flex-col gap-1">${links.map(([label,href])=>`<a href="${href}" class="py-3 px-4 rounded-lg text-base font-medium ${path===href?'bg-amber-50 text-amber-700':'text-stone-700'}">${label}</a>`).join('')}<div class="mt-4 pt-4 border-t border-stone-100 flex flex-col gap-3"><a href="${whatsapp(wa)}" target="_blank" rel="noopener" class="rounded-lg bg-green-50 px-4 py-3 font-medium text-green-700">Chat on WhatsApp</a><a href="booking.html" class="rounded-lg bg-amber-600 px-4 py-3 text-center font-semibold text-white">Book Your Stay</a><a href="my-booking.html" class="py-2 text-center text-sm text-stone-500">View My Booking</a><a href="tel:${phone}" class="py-2 text-center text-sm text-stone-500">Call: ${phone}</a></div></div></div></div>`;
 document.querySelector('#site-footer').innerHTML=`<div class="bg-stone-900 text-stone-300 pt-20 pb-8"><div class="container-lr"><div class="grid grid-cols-1 gap-12 mb-12 md:grid-cols-2 lg:grid-cols-4"><div><h3 class="font-serif text-2xl font-bold text-white">L-Rina Apartment</h3><p class="mb-4 text-sm uppercase tracking-wider text-amber-500">Luxury Short-Stay</p><p class="text-sm leading-relaxed text-stone-400">${settings.tagline||'Comfort, privacy, and a better way to experience Lagos.'}</p></div><div><h4 class="mb-5 text-sm font-semibold uppercase tracking-wider text-white">Explore</h4><ul class="space-y-3">${links.concat([['Bookings','my-booking.html']]).map(([label,href])=>`<li><a href="${href}" class="text-sm text-stone-400 hover:text-amber-500">${label}</a></li>`).join('')}</ul></div><div><h4 class="mb-5 text-sm font-semibold uppercase tracking-wider text-white">Legal</h4><ul class="space-y-3">${[['Privacy Policy','privacy-policy.html'],['Terms & Conditions','terms.html'],['Cancellation Policy','cancellation-policy.html'],['Admin Login','admin.html']].map(([label,href])=>`<li><a href="${href}" class="text-sm text-stone-400 hover:text-amber-500">${label}</a></li>`).join('')}</ul></div><div><h4 class="mb-5 text-sm font-semibold uppercase tracking-wider text-white">Contact</h4><ul class="space-y-4 text-sm"><li class="text-stone-400">${address}</li><li><a href="tel:${phone}" class="text-stone-400 hover:text-amber-500">${phone}</a></li><li><a href="mailto:${email}" class="break-all text-stone-400 hover:text-amber-500">${email}</a></li><li><a href="${whatsapp(wa)}" target="_blank" rel="noopener" class="text-green-400">Chat on WhatsApp</a></li></ul></div></div><div class="flex flex-col items-center justify-between gap-4 border-t border-stone-800 pt-8 md:flex-row"><p class="text-xs text-stone-500">&copy; ${new Date().getFullYear()} L-Rina Apartment. All rights reserved.</p><p class="text-xs text-stone-500">Eti-Osa, Lagos, Nigeria</p></div></div></div><a href="${whatsapp(wa)}" target="_blank" rel="noopener" aria-label="Chat on WhatsApp" class="fixed bottom-6 right-6 z-50 flex h-14 w-14 items-center justify-center rounded-full bg-green-500 text-white shadow-lg transition-transform hover:scale-110"><span class="absolute inset-0 rounded-full bg-green-500 animate-ping opacity-20"></span><span class="relative text-xl">◔</span></a>`;
 const nav=document.querySelector('#site-nav'); const update=()=>{ const scrolled=scrollY>40; nav.classList.toggle('bg-white/95',scrolled); nav.classList.toggle('backdrop-blur-md',scrolled); nav.classList.toggle('shadow-lg',scrolled); nav.classList.toggle('py-3',scrolled); nav.classList.toggle('py-5',!scrolled); nav.querySelectorAll('.nav-link,.nav-brand').forEach(el=>el.classList.toggle('text-stone-900',scrolled)); nav.querySelectorAll('.nav-link').forEach(el=>el.classList.toggle('text-stone-700',scrolled)); nav.querySelector('.nav-accent').classList.toggle('text-amber-700',scrolled); nav.querySelector('.nav-whatsapp').classList.toggle('text-green-700',scrolled); nav.querySelector('#menu-toggle').classList.toggle('text-stone-900',scrolled); }; addEventListener('scroll',update); update();
 const toggle=document.querySelector('#menu-toggle'), drawer=document.querySelector('#mobile-drawer'), overlay=document.querySelector('#mobile-overlay'), panel=document.querySelector('#mobile-panel'); const close=()=>{drawer.classList.add('invisible'); overlay.classList.remove('opacity-100'); panel.classList.add('translate-x-full'); toggle.innerHTML=icon.menu; toggle.setAttribute('aria-expanded','false');}; toggle.addEventListener('click',()=>{const open=drawer.classList.contains('invisible'); if(open){drawer.classList.remove('invisible'); overlay.classList.add('opacity-100'); panel.classList.remove('translate-x-full'); toggle.innerHTML=icon.close; toggle.setAttribute('aria-expanded','true');}else close();}); overlay.addEventListener('click',close); drawer.querySelectorAll('a').forEach(a=>a.addEventListener('click',close)); }
export function toast(message){ const node=document.createElement('div'); node.className='toast'; node.textContent=message; document.body.append(node); setTimeout(()=>node.remove(),3500); }
export const money=value=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(value)||0);
export const nights=(start,end)=>Math.max(1,Math.ceil((new Date(end)-new Date(start))/86400000));
export const ref=(prefix)=>`${prefix}-${Math.floor(10000+Math.random()*90000)}`;
await renderLayout();
