/* L-Rina Apartment: the only JavaScript file used by every HTML page. */

const defaults = {
  phone_display: '08127057823',
  whatsapp_number: '2348127057823',
  email: 'Lrinahomesluxuryapartment8@gmail.com',
  address: 'No 2 Francis Omojiade Crescent, off Howard Edafe Street, Eti-Osa, Lagos 105102, Lagos, Nigeria',
  tagline: 'Comfort, privacy, and a better way to experience Lagos.',
  hero_headline: 'Your private escape in the heart of Lagos',
  hero_subtext: 'Thoughtfully designed short-stay apartments for comfort, privacy, and effortless living.'
};
const roomsFallback = [
  { id: 'deluxe', name: 'Deluxe Room', slug: 'deluxe-room', category: 'Deluxe', description: 'A calm, beautifully finished room with everything you need for a restful Lagos stay.', short_description: 'Comfortable and refined for short stays.', max_guests: 2, bed_type: 'King Bed', room_size: '28 sqm', price_per_night: 85000, amenities: ['Wi-Fi', 'Air conditioning', 'Smart TV', 'Private bathroom'], images: ['https://images.pexels.com/photos/27164969/pexels-photo-27164969.jpeg?auto=compress&cs=tinysrgb&w=1200'], is_available: true },
  { id: 'executive', name: 'Executive Suite', slug: 'executive-suite', category: 'Executive', description: 'More room to settle in, with an elegant lounge area and generous natural light.', short_description: 'Space, privacy, and quiet luxury.', max_guests: 3, bed_type: 'King Bed', room_size: '42 sqm', price_per_night: 125000, amenities: ['Wi-Fi', 'Air conditioning', 'Living area', 'Breakfast'], images: ['https://images.pexels.com/photos/7174113/pexels-photo-7174113.jpeg?auto=compress&cs=tinysrgb&w=1200'], is_available: true },
  { id: 'luxury', name: 'Luxury Apartment', slug: 'luxury-apartment', category: 'Luxury', description: 'Our most spacious apartment for guests who want a complete home-away-from-home experience.', short_description: 'A premium apartment experience in Eti-Osa.', max_guests: 4, bed_type: 'King Bed + Sofa Bed', room_size: '65 sqm', price_per_night: 185000, amenities: ['Wi-Fi', 'Air conditioning', 'Kitchenette', 'Lounge'], images: ['https://images.pexels.com/photos/6585598/pexels-photo-6585598.jpeg?auto=compress&cs=tinysrgb&w=1200'], is_available: true }
];
const menuFallback = [
  { id: 'jollof', name: 'L-Rina Jollof Rice', description: 'Fragrant party jollof with grilled chicken.', price: 8500, category: 'Food', image_url: 'https://images.pexels.com/photos/5409010/pexels-photo-5409010.jpeg?auto=compress&cs=tinysrgb&w=900', is_available: true },
  { id: 'pasta', name: 'Creamy Chicken Pasta', description: 'Penne, tender chicken and parmesan cream.', price: 9500, category: 'Food', image_url: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=900', is_available: true },
  { id: 'grill', name: 'Mixed Grill Platter', description: 'A generous selection from the grill.', price: 14000, category: 'Food', image_url: 'https://images.pexels.com/photos/675951/pexels-photo-675951.jpeg?auto=compress&cs=tinysrgb&w=900', is_available: true },
  { id: 'juice', name: 'Fresh Tropical Juice', description: 'A chilled blend of seasonal fruit.', price: 3500, category: 'Drinks', image_url: 'https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg?auto=compress&cs=tinysrgb&w=900', is_available: true },
  { id: 'water', name: 'Bottled Water', description: 'Chilled still water.', price: 1000, category: 'Drinks', image_url: 'https://images.pexels.com/photos/416528/pexels-photo-416528.jpeg?auto=compress&cs=tinysrgb&w=900', is_available: true }
];
const galleryFallback = ['6585598', '7174113', '8135492', '8146150', '3201921', '8082217'].map((id, index) => ({ id: `gallery-${index}`, title: ['Living room', 'A quiet morning', 'The apartment', 'Lounge details', 'A place to unwind', 'Premium comfort'][index], category: ['Interior', 'Interior', 'Exterior', 'Interior', 'Amenities', 'Rooms'][index], image_url: `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=1200` }));
const heroImages = ['8135492', '7546323', '18285947', '3201921'];
const imageUrl = (id) => `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=1800`;
const amenitiesFallback = ['Wi-Fi', '24-hour power', 'Air conditioning', 'Secure parking', 'Housekeeping', 'In-room dining'].map((name, id) => ({ id, name }));
const reviewsFallback = [{ first_name: 'Amaka', rating: 5, review_text: 'Beautiful, peaceful, and exactly as described. The team made our stay easy.', room_name: 'Executive Suite' }, { first_name: 'Tunde', rating: 5, review_text: 'A very comfortable apartment in a convenient part of Lagos.', room_name: 'Deluxe Room' }];

let supabasePromise;
async function supabase() { const config = window.LRINA_CONFIG || {}; if (!config.supabaseUrl || !config.supabaseAnonKey) return null; supabasePromise ||= import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm').then(({ createClient }) => createClient(config.supabaseUrl, config.supabaseAnonKey)); return supabasePromise; }
async function read(table, fallback, order = 'sort_order') { try { const client = await supabase(); if (!client) return fallback; let query = client.from(table).select('*'); if (order) query = query.order(order, { ascending: true }); const { data, error } = await query; if (error) throw error; return data?.length ? data : fallback; } catch { return fallback; } }
async function settings() { try { const client = await supabase(); if (!client) return defaults; const { data, error } = await client.from('settings').select('*'); if (error) throw error; return { ...defaults, ...Object.fromEntries((data || []).map((row) => [row.key, row.value])) }; } catch { return defaults; } }
const getRooms = () => read('rooms', roomsFallback); const getMenu = () => read('menu_items', menuFallback); const getGallery = () => read('gallery_images', galleryFallback); const getAmenities = () => read('amenities', amenitiesFallback); const getReviews = () => read('reviews', reviewsFallback, null);
async function insert(table, payload) { const client = await supabase(); if (!client) return { ...payload, id: `demo-${Date.now()}` }; const { data, error } = await client.from(table).insert(payload).select().single(); if (error) throw error; return data; }
async function find(table, reference) { try { const client = await supabase(); if (!client) return JSON.parse(localStorage.getItem(`lrina-${table}-${reference}`) || 'null'); const { data, error } = await client.from(table).select('*').eq('reference_number', reference).maybeSingle(); if (error) throw error; return data; } catch { return null; } }
async function update(table, id, payload) { const client = await supabase(); if (!client) return { ...payload, id }; const { data, error } = await client.from(table).update(payload).eq('id', id).select().single(); if (error) throw error; return data; }
const money = (value) => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 }).format(Number(value) || 0);
const stayNights = (start, end) => Math.max(1, Math.ceil((new Date(end) - new Date(start)) / 86400000));
const reference = (prefix) => `${prefix}-${Math.floor(10000 + Math.random() * 90000)}`;
function toast(message) { const node = document.createElement('div'); node.className = 'toast'; node.textContent = message; document.body.append(node); setTimeout(() => node.remove(), 3500); }
const whatsapp = (number) => `https://wa.me/${number}?text=Hello%20L-Rina%20Apartment%2C%20I%20would%20like%20to%20enquire%20about%20availability.`;
function startHeroSlideshow() { let currentImage = 0; const hero = document.querySelector('#hero-bg'); if (!hero) return; hero.style.backgroundImage = `url('${imageUrl(heroImages[0])}')`; setInterval(() => { currentImage = (currentImage + 1) % heroImages.length; hero.style.backgroundImage = `url('${imageUrl(heroImages[currentImage])}')`; }, 6000); }

async function layout() { const config = await settings(); const current = location.pathname.split('/').pop() || 'index.html'; const links = [['Home', 'index.html'], ['Rooms', 'rooms.html'], ['Book Now', 'booking.html'], ['Food & Drinks', 'order.html'], ['Gallery', 'gallery.html'], ['About', 'about.html'], ['Contact', 'contact.html']]; const header = document.querySelector('#site-header'); const footer = document.querySelector('#site-footer');
  if (header) { header.insertAdjacentHTML('afterbegin', `<nav id="site-nav" class="fixed top-0 left-0 right-0 z-50 bg-transparent py-5 transition-all duration-500"><div class="container-lr flex items-center justify-between"><a href="index.html" class="flex items-center gap-2"><span class="font-serif text-2xl font-bold nav-brand">L-Rina</span><span class="text-xs uppercase tracking-[.2em] nav-accent">Apartment</span></a><div class="hidden lg:flex items-center gap-8">${links.map(([label, href]) => `<a href="${href}" class="nav-link text-sm font-medium">${label}</a>`).join('')}</div><div class="hidden lg:flex items-center gap-4"><a href="${whatsapp(config.whatsapp_number)}" class="nav-whatsapp text-sm">WhatsApp</a><a href="booking.html" class="btn-primary text-sm">Book Now</a></div></div></nav>`); }
  if (footer) footer.innerHTML = `<div class="bg-stone-900 text-stone-300 py-20"><div class="container-lr grid gap-12 md:grid-cols-2 lg:grid-cols-4"><div><h3 class="font-serif text-2xl font-bold text-white">L-Rina Apartment</h3><p class="mt-3 text-sm text-stone-400">${config.tagline}</p></div><div><h4 class="text-sm font-semibold uppercase text-white">Explore</h4><ul class="mt-5 space-y-3">${links.concat([['Bookings', 'my-booking.html']]).map(([label, href]) => `<li><a href="${href}" class="text-sm text-stone-400 hover:text-amber-500">${label}</a></li>`).join('')}</ul></div><div><h4 class="text-sm font-semibold uppercase text-white">Legal</h4><ul class="mt-5 space-y-3"><li><a href="privacy-policy.html">Privacy Policy</a></li><li><a href="terms.html">Terms & Conditions</a></li><li><a href="cancellation-policy.html">Cancellation Policy</a></li><li><a href="admin.html">Admin Login</a></li></ul></div><div><h4 class="text-sm font-semibold uppercase text-white">Contact</h4><ul class="mt-5 space-y-3 text-sm text-stone-400"><li>${config.address}</li><li><a href="tel:${config.phone_display}">${config.phone_display}</a></li><li><a href="mailto:${config.email}">${config.email}</a></li><li><a href="${whatsapp(config.whatsapp_number)}" class="text-green-400">Chat on WhatsApp</a></li></ul></div></div></div>`;
  const floatingWhatsApp = document.querySelector('#floating-whatsapp'); if (floatingWhatsApp) floatingWhatsApp.href = whatsapp(config.whatsapp_number);
  const nav = document.querySelector('#site-nav'); addEventListener('scroll', () => nav?.classList.toggle('bg-white/95', scrollY > 40)); const toggle = document.querySelector('#menu-toggle'), drawer = document.querySelector('#mobile-drawer'), overlay = document.querySelector('#mobile-overlay'), panel = document.querySelector('#mobile-panel'); const close = () => { drawer?.classList.add('invisible'); overlay?.classList.remove('opacity-100'); panel?.classList.add('translate-x-full'); }; toggle?.addEventListener('click', () => { const open = drawer.classList.contains('invisible'); drawer.classList.toggle('invisible', !open); overlay.classList.toggle('opacity-100', open); panel.classList.toggle('translate-x-full', !open); toggle.setAttribute('aria-expanded', open); }); overlay?.addEventListener('click', close); drawer?.querySelectorAll('a').forEach((link) => link.addEventListener('click', close)); }

function home() { Promise.all([getRooms(), getAmenities(), getGallery(), getReviews(), settings()]).then(([rooms, amenities, gallery, reviews, config]) => { document.querySelector('#hero-headline').textContent = config.hero_headline; document.querySelector('#hero-subtext').textContent = config.hero_subtext; document.querySelector('#home-rooms').innerHTML = rooms.slice(0, 3).map((r) => `<article class="card-luxury img-zoom"><img src="${r.images?.[0]}" alt="${r.name}" class="h-64 w-full object-cover"><div class="p-6"><p class="text-xs uppercase text-amber-600">${r.category}</p><h3 class="mt-2 font-serif text-3xl font-bold">${r.name}</h3><p class="mt-2 text-sm text-stone-600">${r.short_description || r.description}</p><strong class="mt-5 block">${money(r.price_per_night)} <small>/ night</small></strong></div></article>`).join(''); document.querySelector('#home-amenities').innerHTML = amenities.slice(0, 6).map((a) => `<div class="text-center"><div class="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-amber-100 text-amber-700">✓</div><p class="mt-3 text-sm">${a.name}</p></div>`).join(''); document.querySelector('#home-gallery').innerHTML = gallery.slice(0, 6).map((g) => `<img src="${g.image_url}" alt="${g.title}" class="h-56 w-full rounded-xl object-cover">`).join(''); document.querySelector('#home-reviews').innerHTML = reviews.map((r) => `<blockquote class="rounded-2xl border border-stone-700 p-7"><div class="text-amber-400">${'★'.repeat(r.rating || 5)}</div><p class="mt-4 text-stone-300">“${r.review_text}”</p><footer class="mt-5 text-sm">${r.first_name}</footer></blockquote>`).join(''); startHeroSlideshow(); }); document.querySelector('#availability-form')?.addEventListener('submit', (e) => { e.preventDefault(); const d = new FormData(e.currentTarget); location.href = `rooms.html?guests=${d.get('guests')}&checkin=${d.get('checkin')}&checkout=${d.get('checkout')}`; }); }

function roomsPage() { const list = document.querySelector('#room-list'), empty = document.querySelector('#room-empty'), form = document.querySelector('#room-filter'), guest = document.querySelector('#room-guests'), type = document.querySelector('#room-type'); let rooms = []; getRooms().then((data) => { rooms = data; [...new Set(rooms.map((r) => r.category))].forEach((c) => type.insertAdjacentHTML('beforeend', `<option>${c}</option>`)); render(); }); function render() { const visible = rooms.filter((r) => (!Number(guest.value) || r.max_guests >= Number(guest.value)) && (!type.value || r.category === type.value)); list.innerHTML = visible.map((r) => `<article class="card-luxury img-zoom"><img src="${r.images?.[0]}" alt="${r.name}" class="h-72 w-full object-cover"><div class="p-7"><p class="text-xs uppercase text-amber-600">${r.category}</p><h3 class="mt-2 font-serif text-3xl font-bold">${r.name}</h3><p class="mt-4 text-sm text-stone-600">${r.description}</p><div class="mt-7 flex justify-between"><strong>${money(r.price_per_night)}</strong><a href="booking.html?room=${r.slug}" class="btn-primary px-4 py-2 text-sm">Book</a></div></div></article>`).join(''); empty.classList.toggle('hidden', visible.length > 0); } form?.addEventListener('submit', (e) => { e.preventDefault(); render(); }); }

function bookingPage() { const form = document.querySelector('#booking-form'), room = document.querySelector('#booking-room'), guests = document.querySelector('#booking-guests'), checkIn = document.querySelector('#booking-checkin'), checkOut = document.querySelector('#booking-checkout'), message = document.querySelector('#booking-message'); let rooms = []; getRooms().then((data) => { rooms = data; const p = new URLSearchParams(location.search); room.innerHTML = rooms.map((r) => `<option value="${r.slug}">${r.name} - ${money(r.price_per_night)}/night</option>`).join(''); room.value = p.get('room') || rooms[0].slug; guests.value = p.get('guests') || '1'; checkIn.value = p.get('checkin') || ''; checkOut.value = p.get('checkout') || ''; summary(); }); const selected = () => rooms.find((r) => r.slug === room.value) || rooms[0]; function summary() { const r = selected(); if (!r) return; const n = checkIn.value && checkOut.value ? stayNights(checkIn.value, checkOut.value) : 0; document.querySelector('#summary-room').textContent = r.name; document.querySelector('#summary-in').textContent = checkIn.value || 'Choose a date'; document.querySelector('#summary-out').textContent = checkOut.value || 'Choose a date'; document.querySelector('#summary-guests').textContent = guests.value; document.querySelector('#summary-nights').textContent = n || '-'; document.querySelector('#summary-total').textContent = money(r.price_per_night * n); } [room, guests, checkIn, checkOut].forEach((el) => el?.addEventListener('input', summary)); form?.addEventListener('submit', async (e) => { e.preventDefault(); if (new Date(checkOut.value) <= new Date(checkIn.value)) { message.textContent = 'Check-out must be after check-in.'; return; } const r = selected(), d = new FormData(form), n = stayNights(checkIn.value, checkOut.value), ref = reference('LRINA'); try { const result = await insert('bookings', { reference_number: ref, room_id: r.id, room_name: r.name, full_name: d.get('full_name'), phone: d.get('phone'), email: d.get('email'), num_guests: Number(d.get('guests')), check_in: checkIn.value, check_out: checkOut.value, nights: n, special_requests: d.get('special_requests'), status: 'Pending', payment_status: 'Pending', total_amount: r.price_per_night * n }); localStorage.setItem(`lrina-bookings-${ref}`, JSON.stringify(result)); message.className = 'mt-4 rounded-xl bg-green-50 p-4 text-sm text-green-800'; message.innerHTML = `Booking request received. Reference: <strong>${ref}</strong>.`; } catch { toast('We could not submit the booking.'); } }); }

function orderPage() { const list = document.querySelector('#menu-list'), filters = document.querySelector('#menu-categories'), button = document.querySelector('#cart-button'); let menu = [], cart = JSON.parse(localStorage.getItem('lrina-cart') || '[]'), category = 'All'; const save = () => localStorage.setItem('lrina-cart', JSON.stringify(cart)); const updateCart = () => { const total = cart.reduce((sum, i) => sum + i.price * i.quantity, 0); button.textContent = `Cart (${cart.reduce((sum, i) => sum + i.quantity, 0)}) · ${money(total * 1.1)}`; }; getMenu().then((data) => { menu = data; render(); }); function render() { filters.innerHTML = ['All', ...new Set(menu.map((i) => i.category))].map((c) => `<button data-category="${c}" class="rounded-full px-5 py-2 ${category === c ? 'bg-amber-600 text-white' : 'bg-stone-100'}" type="button">${c}</button>`).join(''); list.innerHTML = menu.filter((i) => i.is_available !== false && (category === 'All' || i.category === category)).map((i) => `<article class="card-luxury"><img src="${i.image_url}" alt="${i.name}" class="h-56 w-full object-cover"><div class="p-6"><p class="text-xs uppercase text-amber-600">${i.category}</p><h3 class="mt-2 font-serif text-3xl font-bold">${i.name}</h3><p class="mt-2 text-sm text-stone-600">${i.description || ''}</p><button data-add="${i.id}" class="btn-primary mt-5 px-4 py-2 text-sm" type="button">Add</button></div></article>`).join(''); filters.querySelectorAll('[data-category]').forEach((b) => b.onclick = () => { category = b.dataset.category; render(); }); list.querySelectorAll('[data-add]').forEach((b) => b.onclick = () => { const i = menu.find((x) => x.id === b.dataset.add), existing = cart.find((x) => x.id === i.id); existing ? existing.quantity++ : cart.push({ id: i.id, name: i.name, price: i.price, quantity: 1 }); save(); updateCart(); toast(`${i.name} added to your cart`); }); updateCart(); } button?.addEventListener('click', () => toast('Open cart controls are managed here.')); }

function galleryPage() { const filters = document.querySelector('#gallery-filters'), grid = document.querySelector('#gallery-grid'); let images = [], category = 'All'; getGallery().then((data) => { images = data; render(); }); function render() { filters.innerHTML = ['All', ...new Set(images.map((i) => i.category))].map((c) => `<button data-filter="${c}" class="rounded-full px-5 py-2 ${category === c ? 'bg-amber-600 text-white' : 'bg-stone-100'}" type="button">${c}</button>`).join(''); grid.innerHTML = images.filter((i) => category === 'All' || i.category === category).map((i) => `<img src="${i.image_url}" alt="${i.title}" class="h-56 w-full rounded-xl object-cover">`).join(''); filters.querySelectorAll('[data-filter]').forEach((b) => b.onclick = () => { category = b.dataset.filter; render(); }); } }
function contactPage() { settings().then((s) => { const details = document.querySelector('#contact-details'); if (!details) return; details.innerHTML = `<p><strong class="block text-stone-900">Address</strong>${s.address}</p><p><strong class="block text-stone-900">Phone</strong><a href="tel:${s.phone_display}" class="text-amber-700">${s.phone_display}</a></p><p><strong class="block text-stone-900">Email</strong><a href="mailto:${s.email}" class="text-amber-700">${s.email}</a></p><a href="${whatsapp(s.whatsapp_number)}" class="btn-whatsapp">Chat on WhatsApp</a>`; document.querySelector('#contact-form').action = `mailto:${s.email}`; }); }
function lookupPage(type) { const booking = type === 'booking', form = document.querySelector('#lookup-form'), result = document.querySelector('#lookup-result'); form.reference.value = new URLSearchParams(location.search).get('ref') || ''; async function search() { const ref = form.reference.value.trim().toUpperCase(); const record = await find(booking ? 'bookings' : 'orders', ref); result.innerHTML = record ? `<article class="card-luxury p-7"><p class="section-subtitle">Reference ${record.reference_number}</p><h2 class="section-title">${booking ? record.room_name : 'Order received'}</h2><p class="mt-5 text-stone-600">Status: ${record.status}</p><p class="mt-2 text-stone-600">Total: ${money(booking ? record.total_amount : record.total)}</p></article>` : '<div class="rounded-xl bg-amber-50 p-6">No record found. Check the reference and try again.</div>'; } form?.addEventListener('submit', (e) => { e.preventDefault(); search(); }); if (form.reference.value) search(); }
function adminPage() { Promise.all([getRooms(), getMenu(), getReviews(), getGallery(), getAmenities()]).then(([a, b, c, d, e]) => { document.querySelector('#admin-cards').innerHTML = [['Rooms', a.length], ['Menu items', b.length], ['Reviews', c.length], ['Gallery images', d.length], ['Amenities', e.length]].map(([label, value]) => `<div class="card-luxury p-6"><p class="text-sm text-stone-500">${label}</p><strong class="mt-2 block text-3xl">${value}</strong></div>`).join(''); }); }

const page = document.body.dataset.page || 'home';
layout();
({ home, rooms: roomsPage, booking: bookingPage, order: orderPage, gallery: galleryPage, about: () => {}, contact: contactPage, 'my-booking': () => lookupPage('booking'), 'order-track': () => lookupPage('order'), admin: adminPage }[page] || (() => {}))();
